### PR TITLE
Change to integer value

### PR DESCRIPTION
**Pull request by jacobchristensen79**
WIP, we improve the search using mongoDB searchable WEIGHT feature ( Text Search ).

### CODE REVIEW

**Comment by hairmare** [comment]
Will this still work with extending schemas ala how ml3k does it? I'm not quite sure and would need to look at the implementation but I assume that the searchable stuff can be overridden in children. 

I'm thinking we might need to have a child definition that wants to deactivate some indexes for a specific case and/or customer. 

Consider a parent definition with these fields.

```
"id": "ParentExample",
"target": {
  "fields": [
    {
      "name": "foo",
      "searchable": true
    }, {
      "name": "bar"
      "searchable": true
     }
  ]
}
```

And its child:

```
"id": "ChildExample",
"service": {
  "parent": "ParentExample",
},
"target": {
  "fields": [
    {
      "name": "bar"
      "searchable": false
    }
  ]
}
```
Isn't this currently a valid way to deactivate indexes?

**Comment by narcoticfresh** [comment]
@hairmare sadly, the ml3k json merging stuff doesn't merge arrays at all.. as he doesn't know any discriminator fields (as `name` in the case of fields) - arrays are simple overwritten if defined in the child..

so this has no impact..

**Comment by narcoticfresh** [comment]
scrutinizer still not finishing here.. ;-/

**Comment by hairmare** [comment]
[Finished](https://scrutinizer-ci.com/g/libgraviton/json-schema/inspections/8cbbf054-a6c0-46fa-a1ec-7fa0eca028d6) but not reporting properly anymore... I'll deactivate the requirement since it's only been a pain lately.

**Pull request merged**
